-- V2__create_categories_table.sql (H2 compatible)
-- Creates the categories table with unique constraint on name

CREATE TABLE categories (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL CONSTRAINT uk_categories_name UNIQUE,
    description CLOB
);

CREATE INDEX idx_categories_name ON categories(name);
